version: "3.8"
services:
  app:
    image: nodeapp:lts
    container_name: notification-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    networks:
      - app_network
networks:
  app_network:
    external: true
